export const FETCH_VIDEOS = "FETCH_VIDEOS";

export const FETCHING_VIDEOS = "FETCHING_VIDEOS";

export const FETCH_VIDEOS_SUCCESS = "FETCH_VIDEOS_SUCCESS";

export const FETCH_VIDEOS_FAILURE = "FETCH_VIDEOS_FAILURE";
